.TH MFTEXT 1
.SH NAME
mftext \- Dump a MIDI file as text
.SH SYNOPSIS
.BI mftext " file"
.SH "DESCRIPTION"
.PP
.B mftext
gives a verbose description of what is in a MIDI file.
You may wish to use it to check the output from
.BR abc2midi .
It is part of the original midifilelib distribution
available from
.IR http://www.harmony-central.com/MIDI/midifilelib.tar.gz .
.SH "SEE ALSO"
.PP
.IR abcmtex "(1), " abc2abc "(1), " abc2midi "(1), " midi2abc "(1)"
.SH AUTHOR
This manual page was written by Anselm Lingnau <lingnau@tm.informatik.uni-frankfurt.de>,
for the Debian GNU/Linux system.
